apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-files
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "drupal-stack.labels" . | nindent 4 }}
    component: drupal
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.drupal.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.drupal.persistence.size }}
